.TH "Fenetre_Jeu" 3 "Mercredi 6 Mai 2020" "Version 2.1" "Fuite de criminels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fenetre_Jeu
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de QWidget\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "QGraphicsScene * \fB_Scene\fP"
.br
.ti -1c
.RI "QGraphicsView * \fB_View\fP"
.br
.ti -1c
.RI "bool \fBFenetre_Apercu\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Fuite de criminels à partir du code source\&.
