.TH "Hitbox" 3 "Mercredi 6 Mai 2020" "Version 2.1" "Fuite de criminels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hitbox
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBHitbox\fP (double const &H, double const &B, double const &G, double const &D)"
.br
.ti -1c
.RI "double \fBgetH\fP () const"
.br
.ti -1c
.RI "double \fBgetB\fP () const"
.br
.ti -1c
.RI "double \fBgetG\fP () const"
.br
.ti -1c
.RI "double \fBgetD\fP () const"
.br
.ti -1c
.RI "void \fBsetH\fP (double const &nouv)"
.br
.ti -1c
.RI "void \fBsetB\fP (double const &nouv)"
.br
.ti -1c
.RI "void \fBsetG\fP (double const &nouv)"
.br
.ti -1c
.RI "void \fBsetD\fP (double const &nouv)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Fuite de criminels à partir du code source\&.
