.TH "NonJoueur" 3 "Mercredi 6 Mai 2020" "Version 2.1" "Fuite de criminels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonJoueur
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBEntite\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNonJoueur\fP (\fBPosition\fP const &pos, Type const &t)"
.br
.ti -1c
.RI "Type \fBgetType\fP () const"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Fuite de criminels à partir du code source\&.
