.TH "Position" 3 "Mercredi 6 Mai 2020" "Version 2.1" "Fuite de criminels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBPosition\fP (double const &x, double const &y)"
.br
.ti -1c
.RI "double \fBgetX\fP () const"
.br
.ti -1c
.RI "void \fBsetX\fP (double const &nouv)"
.br
.ti -1c
.RI "double \fBgetY\fP () const"
.br
.ti -1c
.RI "void \fBsetY\fP (double const &nouv)"
.br
.ti -1c
.RI "\fBPosition\fP \fBoperator+\fP (\fBPosition\fP const &d)"
.br
.ti -1c
.RI "\fBPosition\fP \fBoperator*\fP (double mult)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBPosition\fP const &d)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Fuite de criminels à partir du code source\&.
