.TH "qt_meta_stringdata_Fenetre_Ajout_t" 3 "Mercredi 6 Mai 2020" "Version 2.1" "Fuite de criminels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_Fenetre_Ajout_t
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [12]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [135]"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Fuite de criminels à partir du code source\&.
