.TH "Voleur" 3 "Mercredi 6 Mai 2020" "Version 2.1" "Fuite de criminels" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Voleur
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBJoueur\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBVoleur\fP (\fBPosition\fP const &pos, double speed, std::string nom, Choix_Algo choix)"
.br
.ti -1c
.RI "\fBVoleur\fP * \fBclone\fP () const"
.br
.ti -1c
.RI "void \fBdeplacement\fP () override"
.br
.ti -1c
.RI "\fBGendarme\fP \fBGendarme_Plus_Proche\fP (std::vector< \fBGendarme\fP * > Liste)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Fuite de criminels à partir du code source\&.
